server:
  port: 9999
  context-path: /uaa

security:
  sessions: never

spring:
  application:
      name: uaa-service
  datasource:
    url: jdbc:mysql://localhost:3306/auth?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class: com.mysql.jdbc.Driver
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/