server:
  port: 8082
add-to-db: true
spring:
  application:
    name: process-service
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/process?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    stream:
      bindings:
        documentDeleteOutput:
          destination: documentDeleteInput
          contentType: application/json
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

security:
  oauth2:
    client:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: NEVER

eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/