server:
  port: 8084
spring:
  application:
    name: document-service
#  data:
#    elasticsearch:
#      host: localhost
#      port: 9300
#      cluster-name: documents
#      cluster-nodes: localhost:9200
  http:
    multipart:
     max-file-size: 128KB
     max-request-size: 128KB
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/