server:
  port: 8084
spring:
  application:
    name: document-service
  http:
    multipart:
     max-file-size: 128KB
     max-request-size: 128KB
security:
  oauth2:
    client:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/