server:
  port: 8083
add-to-db: true
spring:
  application:
    name: descriptor-service
  http:
    multipart:
     max-file-size: 128KB
     max-request-size: 128KB
  jpa:
    hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
      auto: create-drop
      use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/descriptor?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
security:
  oauth2:
    client:
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/