server:
  port: 8083
add-to-db: true
spring:
  application:
    name: descriptor-service
  http:
    multipart:
     max-file-size: 1024KB
     max-request-size: 1024KB
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/descriptor?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
security:
  oauth2:
    client:
      clientId: ui2
      clientSecret: ui2-secret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/