spring:
  application:
    name: api-gateway
  aop:
      proxy-target-class: true
server:
  port: 7777
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
zuul:
  routes:
    company-service: /api/company/**
    process-service: /api/process/**
    document-service: /api/document/**
    descriptor-service: /api/descriptor/**
    uaa-service:
      path: /uaa/**
      stripPrefix: false
#      url: http://uaa-service/uaa/user

security:
  oauth2:
    client:
      accessTokenUri: http://uaa-service/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: ui1
      clientSecret: ui1-secret
    resource:
      userInfoUri: http://uaa-service/uaa/user
      preferTokenInfo: false
  sessions: ALWAYS