server:
  port: 9999
  contextPath: /auth

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: admin
    password: admin
    driver-class: com.mysql.jdbc.Driver
#    schema: classpath:/sql/schema.sql
#    data: classpath:/sql/data.sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop